# common configuration for ALL branches
image: Visual Studio 2017
install:
  - choco install gitversion.portable -pre -y
  - ps: (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex  
test: off
assembly_info:
  patch: false
environment:
  VERSION_INFO_SEMVER: null
  VERSION_INFO: null
  VERSION_INFO_NUGET: null
nuget:
  disable_publish_on_pr: true

before_build: 
- ps: >-
    $version_info_json = (gitversion /l console /output json);
    $version_info = (gitversion /output json | ConvertFrom-Json);
    $env:VERSION = $version_info;
    $env:VERSION_INFO = $version_info;
    $env:VERSION_INFO_SEMVER = $version_info.SemVer;
    $env:VERSION_INFO_NUGET = $version_info.NuGetVersion;
    
    Update-AppveyorBuild -Version "$env:VERSION_INFO_SEMVER";

    $vsixManifest = "extension.vsixmanifest";
    [xml]$vsixXml = Get-Content $vsixManifest;

    $ns = New-Object System.Xml.XmlNamespaceManager $vsixXml.NameTable;
    $ns.AddNamespace("ns", $vsixXml.DocumentElement.NamespaceURI) | Out-Null;

    $attrVersion = "";

    if ($vsixXml.SelectSingleNode("//ns:Identity", $ns)){ # VS2012 format
        $attrVersion = $vsixXml.SelectSingleNode("//ns:Identity", $ns).Attributes["Version"];
    }
    elseif ($vsixXml.SelectSingleNode("//ns:Version", $ns)){ # VS2010 format
        $attrVersion = $vsixXml.SelectSingleNode("//ns:Version", $ns);
    }

    $attrVersion.InnerText = $version_info.SemVer;

    $vsixXml.Save($vsixManifest) | Out-Null;

    $version.ToString() | Write-Host -ForegroundColor Green;

    Write-Host "Get GitVersion output = " $version_info_json;
    Write-Host "Set VERSION_INFO_SEMVER = " $env:VERSION_INFO_SEMVER;
    Write-Host "Set APPVEYOR_BUILD_VERSION = " $env:APPVEYOR_BUILD_VERSION;
    # Vsix-IncrementVsixVersion | Vsix-UpdateBuildVersion;

  # - ps: gitversion /l console /output buildserver  
  # - ps: $version = $env:GitVersion_SemVer
  # - ps: WRITE-HOST $version
  # - ps: $env:APPVEYOR_BUILD_VERSION = $version
  # - ps: WRITE-HOST "$env:APPVEYOR_BUILD_VERSION"
  # - ps: Update-AppveyorBuild -Version "$version"
  # - ps: Vsix-IncrementVsixVersion | Vsix-UpdateBuildVersion
cache:
  - packages -> **\packages.config
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml

for:
-
  branches:
# IMPORTANT: Building a TAG is on a branch with the TAG name. So this does not work
    only:
      - /\d+\.\d+\.\d+$/
  build_script:
    - build.bat /t:Build /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m
  skip_non_tags: true

# all other branches
-
  build_script:
    - build.bat /t:Build /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m
 
after_build:
  # - ps: Vsix-PushArtifacts | Vsix-PublishToGallery