# common configuration for ALL branches
image: Visual Studio 2017
install:
  - choco install gitversion.portable -pre -y
  - ps: (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex  
test: off
assembly_info:
  patch: false
# environment:
#   VERSION_INFO_SEMVER: null
#   VERSION_INFO: null
#   VERSION_INFO_NUGET: null
nuget:
  disable_publish_on_pr: true
# Start builds on tags only (GitHub and BitBucket)
# skip_non_tags: true

before_build: 
  - ps: Vsix-IncrementVsixVersion | Vsix-UpdateBuildVersion
  - ps: >-
    $manifestFiles = Get-ChildItem -Filter *.vsixmanifest -Recurse;
    foreach ($vsixManifest in $manifestFiles)
    {
      Write-Host $vsixManifest.Fullname -ForegroundColor Yellow;  

      $vsixXmlAsText = Get-Content $vsixManifest;
      Write-Host $vsixXmlAsText -ForegroundColor Yellow;
    }        

cache:
  - packages -> **\packages.config
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml

build_script:
  - build.bat /t:Build /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m

#after_build:
  # - ps: Vsix-PushArtifacts | Vsix-PublishToGallery